
%% make thermal lag correction for each profile based on the thermal_lag_flag
% 0: no correction
% 1: correction in T/S (or normalized T/S) space
% 2: correction in in Pressure (depth) - Salinity space, adjusted to
% thermocline dpeth.

% high level processure for each profile:
% 1. identify which thermal lag
% correction method to use.
% 2. identify whether it is a downcast or
% upcast, and choose the corresponding upcast or downcast to pair with.
% The pairing profile should be either the previous profile or the next
% profile adjacent to the current profile.
% 3. perform pair-wise thermal lag correction for this current profile.
% 4. calculate derivative variables (corrected salinity, density, etc.) for
% the profile.

clear cor_profile

% count of how many profiles that actually needed thermal lag corrrection
count_cor = 0;

for iter = 1:n_profiles

    % temporary vectors for calculation
    working_downcast = [];
    working_upcast = [];
    ThermalLagParams = [];

    % count_cor increases by 1 if the profile needs to be corrected
    if profile(iter).thermal_lag_flag ~= 0
        count_cor = count_cor + 1;
    end

    % correction for profiles that are neither the first or the final
    % profile in the glider mission
    if iter>1 && iter<n_profiles

        % if thermal_lag_flag == 1, use the TS based method
        if profile(iter).thermal_lag_flag == 1

            % if the profile is a downcast
            if profile(iter).direction == 1
                working_downcast = profile(iter);
                % find the upcast for using pair-wise correction (either
                % previous cast or next cast)
                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) <= abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_upcast = profile(iter+1);
                end

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) > abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_upcast = profile(iter-1);
                end

                ThermalLagParams = ...
                    findThermalLagParams_TS_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure, ...
                    working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_downcast.salt_outside = ...
                    gsw_SP_from_C(working_downcast.cond_outside*10, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_downcast.saltA_outside = ...
                    gsw_SA_from_SP(working_downcast.salt_outside, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.longitude,working_downcast.latitude); % absolute salinity, pressure is in dbar

                working_downcast.ctemp_outside = ...
                    gsw_CT_from_t(working_downcast.saltA_outside, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_downcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential temperature

                working_downcast.rho_outside = ...
                    gsw_rho(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside, ...
                    working_downcast.pressure_lag_shifted); % in-situ density

                working_downcast.sigma0_outside = ...
                    gsw_sigma0(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_downcast;

            end

            % if the profile is an upcast
            if profile(iter).direction == -1
                working_upcast = profile(iter);

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) <= abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_downcast = profile(iter+1);
                end

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) > abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_downcast = profile(iter-1);
                end

                ThermalLagParams = ...
                    findThermalLagParams_TS_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure, ...
                    working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_upcast.salt_outside = ...
                    gsw_SP_from_C(working_upcast.cond_outside*10, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_upcast.saltA_outside = ...
                    gsw_SA_from_SP(working_upcast.salt_outside, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.longitude,working_upcast.latitude); % absolute salinity, pressure is in dbar

                working_upcast.ctemp_outside = ...
                    gsw_CT_from_t(working_upcast.saltA_outside, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_upcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential temperature

                working_upcast.rho_outside = ...
                    gsw_rho(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside, ...
                    working_upcast.pressure_lag_shifted); % in-situ density

                working_upcast.sigma0_outside = ...
                    gsw_sigma0(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_upcast;
            end

        end

        % if thermal_lag_flag == 2, use the Sality-pressure based method
        % (adjusted to thermocline depth)

        if profile(iter).thermal_lag_flag == 2

            % if the profile is a downcast
            if profile(iter).direction == 1
                working_downcast = profile(iter);

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) <= abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_upcast = profile(iter+1);
                end

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) > abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_upcast = profile(iter-1);
                end

                ThermalLagParams = ...
                    findThermalLagParams_SP_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure, ...
                    working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);


                working_downcast.salt_outside = ...
                    gsw_SP_from_C(working_downcast.cond_outside*10, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_downcast.saltA_outside = ...
                    gsw_SA_from_SP(working_downcast.salt_outside, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.longitude,working_downcast.latitude); % absolute salinity, pressure is in dbar

                working_downcast.ctemp_outside = ...
                    gsw_CT_from_t(working_downcast.saltA_outside, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_downcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential temperature

                working_downcast.rho_outside = ...
                    gsw_rho(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside, ...
                    working_downcast.pressure_lag_shifted); % in-situ density

                working_downcast.sigma0_outside = ...
                    gsw_sigma0(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_downcast;

            end

            % if the profile is a upcast
            if profile(iter).direction == -1
                working_upcast = profile(iter);

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) <= abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_downcast = profile(iter+1);
                end

                if abs(mean(profile(iter).profile_time) - mean(profile(iter+1).profile_time)) > abs(mean(profile(iter).profile_time) - profile(iter-1).profile_time)
                    working_downcast = profile(iter-1);
                end


                ThermalLagParams = ...
                    findThermalLagParams_SP_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure, ...
                    working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);


                working_upcast.salt_outside = ...
                    gsw_SP_from_C(working_upcast.cond_outside*10, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_upcast.saltA_outside = ...
                    gsw_SA_from_SP(working_upcast.salt_outside, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.longitude,working_upcast.latitude); % absolute salinity, pressure is in dbar

                working_upcast.ctemp_outside = ...
                    gsw_CT_from_t(working_upcast.saltA_outside, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_upcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential temperature

                working_upcast.rho_outside = ...
                    gsw_rho(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside, ...
                    working_upcast.pressure_lag_shifted); % in-situ density

                working_upcast.sigma0_outside = ...
                    gsw_sigma0(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_upcast;
            end

        end

    end

    % correction for the first profile in the glider mission
    if iter==1

        % if thermal_lag_flag == 1, use the T/S based method
        if profile(iter).thermal_lag_flag == 1

            % if the profile is a downcast
            if profile(iter).direction == 1
                working_downcast = profile(iter);

                working_upcast = profile(iter+1);

                ThermalLagParams = ...
                    findThermalLagParams_TS_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure, ...
                    working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);


                working_downcast.salt_outside = ...
                    gsw_SP_from_C(working_downcast.cond_outside*10, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_downcast.saltA_outside = ...
                    gsw_SA_from_SP(working_downcast.salt_outside, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.longitude,working_downcast.latitude); % absolute salinity, pressure is in dbar

                working_downcast.ctemp_outside = ...
                    gsw_CT_from_t(working_downcast.saltA_outside, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_downcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential temperature

                working_downcast.rho_outside = ...
                    gsw_rho(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside, ...
                    working_downcast.pressure_lag_shifted); % in-situ density

                working_downcast.sigma0_outside = ...
                    gsw_sigma0(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_downcast;

            end

            % if the profile is a upcast
            if profile(iter).direction == -1
                working_upcast = profile(iter);

                working_downcast = profile(iter+1);

                ThermalLagParams = ...
                    findThermalLagParams_TS_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure, ...
                    working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_upcast.salt_outside = ...
                    gsw_SP_from_C(working_upcast.cond_outside*10, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_upcast.saltA_outside = ...
                    gsw_SA_from_SP(working_upcast.salt_outside, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.longitude,working_upcast.latitude); % absolute salinity, pressure is in dbar

                working_upcast.ctemp_outside = ...
                    gsw_CT_from_t(working_upcast.saltA_outside, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_upcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential temperature

                working_upcast.rho_outside = ...
                    gsw_rho(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside, ...
                    working_upcast.pressure_lag_shifted); % in-situ density

                working_upcast.sigma0_outside = ...
                    gsw_sigma0(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_upcast;
            end

        end

        % if thermal_lag_flag == 2, use the Sality-pressure based method
        % (adjusted to thermocline depth)

        if profile(iter).thermal_lag_flag == 2

            % if the profile is a downcast
            if profile(iter).direction == 1
                working_downcast = profile(iter);

                working_upcast = profile(iter+1);

                ThermalLagParams = ...
                    findThermalLagParams_SP_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure, ...
                    working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_downcast.salt_outside = ...
                    gsw_SP_from_C(working_downcast.cond_outside*10, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_downcast.saltA_outside = ...
                    gsw_SA_from_SP(working_downcast.salt_outside, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.longitude,working_downcast.latitude); % absolute salinity, pressure is in dbar

                working_downcast.ctemp_outside = ...
                    gsw_CT_from_t(working_downcast.saltA_outside, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_downcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential temperature

                working_downcast.rho_outside = ...
                    gsw_rho(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside, ...
                    working_downcast.pressure_lag_shifted); % in-situ density

                working_downcast.sigma0_outside = ...
                    gsw_sigma0(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_downcast;

            end

            % if the profile is a upcast
            if profile(iter).direction == -1
                working_upcast = profile(iter);
                working_downcast = profile(iter+1);

                ThermalLagParams = ...
                    findThermalLagParams_SP_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure, ...
                    working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_upcast.salt_outside = ...
                    gsw_SP_from_C(working_upcast.cond_outside*10, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_upcast.saltA_outside = ...
                    gsw_SA_from_SP(working_upcast.salt_outside, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.longitude,working_upcast.latitude); % absolute salinity, pressure is in dbar

                working_upcast.ctemp_outside = ...
                    gsw_CT_from_t(working_upcast.saltA_outside, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_upcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential temperature

                working_upcast.rho_outside = ...
                    gsw_rho(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside, ...
                    working_upcast.pressure_lag_shifted); % in-situ density

                working_upcast.sigma0_outside = ...
                    gsw_sigma0(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_upcast;
            end

        end

    end


    if iter==n_profiles

        % if thermal_lag_flag == 1, use the T/S based method

        if profile(iter).thermal_lag_flag == 1
            % if the profile is a downcast
            if profile(iter).direction == 1
                working_downcast = profile(iter);

                working_upcast = profile(iter-1);

                ThermalLagParams = ...
                    findThermalLagParams_TS_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure, ...
                    working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_downcast.salt_outside = ...
                    gsw_SP_from_C(working_downcast.cond_outside*10, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_downcast.saltA_outside = ...
                    gsw_SA_from_SP(working_downcast.salt_outside, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.longitude,working_downcast.latitude); % absolute salinity, pressure is in dbar

                working_downcast.ctemp_outside = ...
                    gsw_CT_from_t(working_downcast.saltA_outside, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_downcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential temperature

                working_downcast.rho_outside = ...
                    gsw_rho(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside, ...
                    working_downcast.pressure_lag_shifted); % in-situ density

                working_downcast.sigma0_outside = ...
                    gsw_sigma0(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_downcast;

            end

            % if the profile is a upcast
            if profile(iter).direction == -1
                working_upcast = profile(iter);

                working_downcast = profile(iter-1);

                ThermalLagParams = ...
                    findThermalLagParams_TS_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure, ...
                    working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_upcast.salt_outside = ...
                    gsw_SP_from_C(working_upcast.cond_outside*10, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_upcast.saltA_outside = ...
                    gsw_SA_from_SP(working_upcast.salt_outside, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.longitude,working_upcast.latitude); % absolute salinity, pressure is in dbar

                working_upcast.ctemp_outside = ...
                    gsw_CT_from_t(working_upcast.saltA_outside, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_upcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential temperature

                working_upcast.rho_outside = ...
                    gsw_rho(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside, ...
                    working_upcast.pressure_lag_shifted); % in-situ density

                working_upcast.sigma0_outside = ...
                    gsw_sigma0(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_upcast;
            end

        end

        % if thermal_lag_flag == 2, use the Sality-pressure based method
        % (adjusted to thermocline depth)

        if profile(iter).thermal_lag_flag == 2

            % if the profile is a downcast
            if profile(iter).direction == 1
                working_downcast = profile(iter);
                working_upcast = profile(iter-1);

                ThermalLagParams = ...
                    findThermalLagParams_SP_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure, ...
                    working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                working_downcast.salt_outside = ...
                    gsw_SP_from_C(working_downcast.cond_outside*10, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_downcast.saltA_outside = ...
                    gsw_SA_from_SP(working_downcast.salt_outside, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.longitude,working_downcast.latitude); % absolute salinity, pressure is in dbar

                working_downcast.ctemp_outside = ...
                    gsw_CT_from_t(working_downcast.saltA_outside, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_downcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential temperature

                working_downcast.rho_outside = ...
                    gsw_rho(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside, ...
                    working_downcast.pressure_lag_shifted); % in-situ density

                working_downcast.sigma0_outside = ...
                    gsw_sigma0(working_downcast.saltA_outside, ...
                    working_downcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_downcast;

            end

            % if the profile is a upcast
            if profile(iter).direction == -1
                working_upcast = profile(iter);
                working_downcast = profile(iter-1);

                ThermalLagParams = ...
                    findThermalLagParams_SP_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.thermocline_pressure, ...
                    working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    working_downcast.pressure_lag_shifted, ...
                    working_downcast.thermocline_pressure);

                alpha(iter) = ThermalLagParams(1);
                tau(iter) = ThermalLagParams(2);

                [working_upcast.temp_inside, working_upcast.cond_outside] = ...
                    correctThermalLag_haixing(working_upcast.ctd_time, ...
                    working_upcast.conductivity_lag_shifted, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);

                [working_downcast.temp_inside, working_downcast.cond_outside] = ...
                    correctThermalLag_haixing(working_downcast.ctd_time, ...
                    working_downcast.conductivity_lag_shifted, ...
                    working_downcast.temperature_response_corrected_smooth, ...
                    ThermalLagParams);


                working_upcast.salt_outside = ...
                    gsw_SP_from_C(working_upcast.cond_outside*10, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.

                working_upcast.saltA_outside = ...
                    gsw_SA_from_SP(working_upcast.salt_outside, ...
                    working_upcast.pressure_lag_shifted, ...
                    working_upcast.longitude,working_upcast.latitude); % absolute salinity, pressure is in dbar

                working_upcast.ctemp_outside = ...
                    gsw_CT_from_t(working_upcast.saltA_outside, ...
                    working_upcast.temperature_response_corrected_smooth, ...
                    working_upcast.pressure_lag_shifted); % conservative temperature, pressure is in dbar

                working_upcast.ptemp_outside = ...
                    gsw_pt_from_CT(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential temperature

                working_upcast.rho_outside = ...
                    gsw_rho(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside, ...
                    working_upcast.pressure_lag_shifted); % in-situ density

                working_upcast.sigma0_outside = ...
                    gsw_sigma0(working_upcast.saltA_outside, ...
                    working_upcast.ctemp_outside); % potential density anomaly

                cor_profile(count_cor) = working_upcast;
            end

        end

    end

end

%% get alpha and tau values used for thermal lag correction for each profile

cor_alpha = alpha(alpha~=0);
cor_tau = alpha(tau~=0);

