
% find alpha and tau based on each yo (pair of down and up profiles)


%%
% Method using Glider toolbox to find conductivity thermal lag correction parameters
% seemingly, this produces the best result as of May 27, 2021
% this algorithm uses globally shifted conductivity data, ie. conductivity_lag_shifted,
% conductivity_lag_shifted here is by pressure sensor shift
% the method that shift conductivity based on gloabl bias between up and down conductivity data produced bad results

%% use glider_toolbox_master findThermalLagParams_haixing.m and correctThermalLag.m to correct thermal lag for conductivity cell
% Note this step, thermal lag correction, is for conductivity measurements



% in the conductivity cell.
% option 2, use time shifted conductivity

for segment_id = 1:n_segment
 
for iter = 1:segment2(segment_id).n_pair    
    
    segment2(segment_id).profile_pair(iter).ThermalLagParams = ...
        findThermalLagParams_SP_haixing(segment2(segment_id).downcast(iter).ctd_time, ...
        segment2(segment_id).downcast(iter).conductivity_lag_shifted, ...
        segment2(segment_id).downcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted, ...
        segment2(segment_id).downcast(iter).thermocline_pressure, ...
        segment2(segment_id).upcast(iter).ctd_time, ...
        segment2(segment_id).upcast(iter).conductivity_lag_shifted, ...
        segment2(segment_id).upcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted, ...
        segment2(segment_id).upcast(iter).thermocline_pressure);
    
    segment2(segment_id).alpha(iter) = segment2(segment_id).profile_pair(iter).ThermalLagParams(1);
    segment2(segment_id).tau(iter) = segment2(segment_id).profile_pair(iter).ThermalLagParams(2);
    
    [segment2(segment_id).downcast(iter).temp_inside, segment2(segment_id).downcast(iter).cond_outside] = ...
        correctThermalLag_haixing(segment2(segment_id).downcast(iter).ctd_time, ...
        segment2(segment_id).downcast(iter).conductivity_lag_shifted, ...
        segment2(segment_id).downcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).profile_pair(iter).ThermalLagParams);
        
    [segment2(segment_id).upcast(iter).temp_inside, segment2(segment_id).upcast(iter).cond_outside] = ...
        correctThermalLag_haixing(segment2(segment_id).upcast(iter).ctd_time, ...
        segment2(segment_id).upcast(iter).conductivity_lag_shifted, ...
        segment2(segment_id).upcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).profile_pair(iter).ThermalLagParams);
end % for ii = 1:segment2(segment_id).n_pair


%% Use corrected temmperature inside the conductivity cell
...and conductivity inside the conductivity cell to calculate salinity
    
% need to double check how potential density is calculated, with which temperature

tic
for iter = 1:segment2(segment_id).n_pair
    
%     iter
    % adjust negative pressure (above surface) to use gsw_SA_from_SP.m
        segment2(segment_id).downcast(iter).pressure_lag_shifted(segment2(segment_id).downcast(iter).pressure_lag_shifted<-0.1) = -0.1;
    segment2(segment_id).upcast(iter).pressure_lag_shifted(segment2(segment_id).upcast(iter).pressure_lag_shifted< -0.1) = -0.1;
   
    % segment_downs
    
    segment2(segment_id).downcast(iter).salt_inside = ...
        gsw_SP_from_C(segment2(segment_id).downcast(iter).conductivity_lag_shifted*10, ...
        segment2(segment_id).downcast(iter).temp_inside, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.
    
    segment2(segment_id).downcast(iter).saltA_inside = ...
        gsw_SA_from_SP(segment2(segment_id).downcast(iter).salt_inside, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted, ...
        segment2(segment_id).downcast(iter).longitude,segment2(segment_id).downcast(iter).latitude); % absolute salinity, pressure is in dbar
    
    segment2(segment_id).downcast(iter).ctemp_inside = ...
        gsw_CT_from_t(segment2(segment_id).downcast(iter).saltA_inside, ...
        segment2(segment_id).downcast(iter).temp_inside, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted); % conservative temperature, pressure is in dbar
    
    segment2(segment_id).downcast(iter).ptemp_inside = ...
        gsw_pt_from_CT(segment2(segment_id).downcast(iter).saltA_inside, ...
        segment2(segment_id).downcast(iter).ctemp_inside); % potential temperature
    
    segment2(segment_id).downcast(iter).rho_inside = ...
        gsw_rho(segment2(segment_id).downcast(iter).saltA_inside, ...
        segment2(segment_id).downcast(iter).ctemp_inside, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted); % in-situ density
    
    segment2(segment_id).downcast(iter).sigma0_inside = ...
        gsw_sigma0(segment2(segment_id).downcast(iter).saltA_inside, ...
        segment2(segment_id).downcast(iter).ctemp_inside); % potential density anomaly
    
    
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % segment_ups
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
       segment2(segment_id).upcast(iter).salt_inside = ...
        gsw_SP_from_C(segment2(segment_id).upcast(iter).conductivity_lag_shifted*10, ...
        segment2(segment_id).upcast(iter).temp_inside, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.
    
    segment2(segment_id).upcast(iter).saltA_inside = ...
        gsw_SA_from_SP(segment2(segment_id).upcast(iter).salt_inside, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted, ...
        segment2(segment_id).upcast(iter).longitude,segment2(segment_id).upcast(iter).latitude); % absolute salinity, pressure is in dbar
    
    segment2(segment_id).upcast(iter).ctemp_inside = ...
        gsw_CT_from_t(segment2(segment_id).upcast(iter).saltA_inside, ...
        segment2(segment_id).upcast(iter).temp_inside, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted); % conservative temperature, pressure is in dbar
    
    segment2(segment_id).upcast(iter).ptemp_inside = ...
        gsw_pt_from_CT(segment2(segment_id).upcast(iter).saltA_inside, ...
        segment2(segment_id).upcast(iter).ctemp_inside); % potential temperature
    
    segment2(segment_id).upcast(iter).rho_inside = ...
        gsw_rho(segment2(segment_id).upcast(iter).saltA_inside, ...
        segment2(segment_id).upcast(iter).ctemp_inside, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted); % in-situ density
    
    segment2(segment_id).upcast(iter).sigma0_inside = ...
        gsw_sigma0(segment2(segment_id).upcast(iter).saltA_inside, ...
        segment2(segment_id).upcast(iter).ctemp_inside); % potential density anomaly
    
    
    end % for ii = 1:segment2(segment_id).n_pair
   
    toc
    %% Use corrected temperature and conductivity outside of the conductivity cell
 tic   

for iter = 1:segment2(segment_id).n_pair
    
%     iter
    % adjust negative pressure (above surface) to use gsw_SA_from_SP
        segment2(segment_id).downcast(iter).pressure_lag_shifted(segment2(segment_id).downcast(iter).pressure_lag_shifted<-0.1) = -0.1;
    segment2(segment_id).upcast(iter).pressure_lag_shifted(segment2(segment_id).upcast(iter).pressure_lag_shifted< -0.1) = -0.1;
   
    % segment_downs
    
    segment2(segment_id).downcast(iter).salt_outside = ...
        gsw_SP_from_C(segment2(segment_id).downcast(iter).cond_outside*10, ...
        segment2(segment_id).downcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.
    
    segment2(segment_id).downcast(iter).saltA_outside = ...
        gsw_SA_from_SP(segment2(segment_id).downcast(iter).salt_outside, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted, ...
        segment2(segment_id).downcast(iter).longitude,segment2(segment_id).downcast(iter).latitude); % absolute salinity, pressure is in dbar
    
    segment2(segment_id).downcast(iter).ctemp_outside = ...
        gsw_CT_from_t(segment2(segment_id).downcast(iter).saltA_outside, ...
        segment2(segment_id).downcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted); % conservative temperature, pressure is in dbar
    
    segment2(segment_id).downcast(iter).ptemp_outside = ...
        gsw_pt_from_CT(segment2(segment_id).downcast(iter).saltA_outside, ...
        segment2(segment_id).downcast(iter).ctemp_outside); % potential temperature
    
    segment2(segment_id).downcast(iter).rho_outside = ...
        gsw_rho(segment2(segment_id).downcast(iter).saltA_outside, ...
        segment2(segment_id).downcast(iter).ctemp_outside, ...
        segment2(segment_id).downcast(iter).pressure_lag_shifted); % in-situ density
    
    segment2(segment_id).downcast(iter).sigma0_outside = ...
        gsw_sigma0(segment2(segment_id).downcast(iter).saltA_outside, ...
        segment2(segment_id).downcast(iter).ctemp_outside); % potential density anomaly
    
    
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % segment_ups
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
      segment2(segment_id).upcast(iter).salt_outside = ...
        gsw_SP_from_C(segment2(segment_id).upcast(iter).cond_outside*10, ...
        segment2(segment_id).upcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted); % salinity, pressure is in dbar and conductivity from S/m to mS/cm.
    
    segment2(segment_id).upcast(iter).saltA_outside = ...
        gsw_SA_from_SP(segment2(segment_id).upcast(iter).salt_outside, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted, ...
        segment2(segment_id).upcast(iter).longitude,segment2(segment_id).upcast(iter).latitude); % absolute salinity, pressure is in dbar
    
    segment2(segment_id).upcast(iter).ctemp_outside = ...
        gsw_CT_from_t(segment2(segment_id).upcast(iter).saltA_outside, ...
        segment2(segment_id).upcast(iter).temperature_response_corrected_smooth, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted); % conservative temperature, pressure is in dbar
    
    segment2(segment_id).upcast(iter).ptemp_outside = ...
        gsw_pt_from_CT(segment2(segment_id).upcast(iter).saltA_outside, ...
        segment2(segment_id).upcast(iter).ctemp_outside); % potential temperature
    
    segment2(segment_id).upcast(iter).rho_outside = ...
        gsw_rho(segment2(segment_id).upcast(iter).saltA_outside, ...
        segment2(segment_id).upcast(iter).ctemp_outside, ...
        segment2(segment_id).upcast(iter).pressure_lag_shifted); % in-situ density
    
    segment2(segment_id).upcast(iter).sigma0_outside = ...
        gsw_sigma0(segment2(segment_id).upcast(iter).saltA_outside, ...
        segment2(segment_id).upcast(iter).ctemp_outside); % potential density anomaly
    
    
    end % for ii = 1:segment2(segment_id).n_pair
    toc
    
    % status
    segment_id
    
end

%%
save RU28_workspace2.mat

% save('RU28_segment_data.mat', 'segment_down', 'segment_up', 'segment_data')


